"""把线上 Flask 大屏响应与已校验的 Spark 导出结果逐项对账。

输入：ADS 导出目录和正在运行的 ``/api/v1/dashboard`` 地址。
输出/接口：检查十组值、批次来源和脚本 SHA256；不一致时返回失败退出码。
"""
import argparse
import json
from decimal import Decimal
from pathlib import Path
from urllib.request import urlopen
from ads_common import TABLES, validate_export, digest

GROUPS = dict(zip(TABLES, ('overview', 'user_levels', 'user_radar', 'platforms',
                         'hour_trend', 'station_types', 'week_compare',
                         'battery_health', 'area_costs', 'top_stations')))


def canonical(value):
    if isinstance(value, dict):
        return {key: canonical(item) for key, item in value.items()}
    if isinstance(value, list):
        return [canonical(item) for item in value]
    if isinstance(value, (int, float, Decimal)) and not isinstance(value, bool):
        return Decimal(str(value))
    return value


def verify(directory, payload):
    manifest, tables = validate_export(directory)
    if payload.get('code') != 0:
        raise ValueError('API reports failure')
    metadata = payload.get('metadata', {})
    if not metadata.get('batch_id'):
        raise ValueError('API has no imported batch identity')
    for field in ('analysis', 'quality', 'tables', 'generated_at'):
        if canonical(metadata.get(field)) != canonical(manifest.get(field)):
            raise ValueError(f'API metadata differs from local export: {field}')
    if manifest['analysis']['script_sha256'] != digest(Path(__file__).with_name('evcharging_analysis.py')):
        raise ValueError('Export was generated by a different analysis script; rebuild first')
    data = payload.get('data', {})
    for table, group in GROUPS.items():
        raw = [data.get(group)] if group == 'overview' else data.get(group)
        if not isinstance(raw, list) or any(not isinstance(row, dict) for row in raw):
            raise ValueError(f'{group}: invalid API rows')
        actual = []
        for row in raw:
            values = []
            for name, kind in TABLES[table]['columns']:
                if name not in row:
                    raise ValueError(f'{group}: missing field {name}')
                value = row[name]
                if value is not None and not kind.startswith('varchar'):
                    if isinstance(value, bool):
                        raise ValueError(f'{group}.{name}: boolean is not numeric')
                    value = Decimal(str(value))
                values.append(value)
            actual.append(tuple(values))
        # Decimal equals integers; preserve NULL and compare every field, independent of SQL sorting.
        if sorted(actual, key=repr) != sorted(tables[table], key=repr):
            # repr distinguishes Decimal/int; use matching by equality instead.
            remaining = list(tables[table])
            for row in actual:
                if row not in remaining:
                    raise ValueError(f'{group}: API values differ from Spark CSV')
                remaining.remove(row)
            if remaining:
                raise ValueError(f'{group}: API is missing exported rows')
    return metadata['batch_id']


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--dir', required=True, type=Path)
    parser.add_argument('--base-url', default='http://127.0.0.1:8091')
    args = parser.parse_args()
    try:
        with urlopen(args.base_url.rstrip('/') + '/api/v1/dashboard', timeout=15) as response:
            payload = json.loads(response.read(), parse_float=Decimal)
        batch = verify(args.dir.resolve(), payload)
        print(f'PASS: all ten API groups equal the Spark export; batch={batch}')
    except Exception as exc:
        raise SystemExit(f'FAILED: {exc}')
